### ISSUE TITLE
On fresh install I get a service worker error when installing the unpacked extension

### ISSUE THREAD

**Issue by chandlerwilcox88** [mubaidr/vite-vue3-chrome-extension#14] opened 2023-05-22 19:27 UTC
I am running `pnpm dev` in the console with no errors but when I look in the chrome extensions I see this error. Any ideas on how to fix?

<img width="508" alt="Screen Shot 2023-05-22 at 12 26 28 PM" src="https://github.com/mubaidr/vite-vue3-chrome-extension-v3/assets/7296169/31e39398-179b-4c6f-88df-f7c24b63bbb1">

**Comment by schlunsen** [comment] 2023-05-23 10:16
Same here

**Comment by mubaidr** [comment] 2023-05-23 10:18
I will look into this matter

**Comment by stone89son** [comment] 2023-05-24 11:34
Same problem.

**Comment by mubaidr** [comment] 2023-05-26 10:22
I am unable to reproduce this issue. Can you please try clean install with latest template from github?

Closing as cannot reproduct this error.

**Closed as completed** 2023-05-31 07:45 UTC
